Repository predis/predis, pull requests merged in 2020-08, with the labels that each got.

#556 Iterate not iterable connections
  src/Client.php
  tests/Predis/ClientTest.php
Labels: feature

#497 Correcting the return type hint for BRPOPLPUSH method
  src/ClientInterface.php
Labels: documentation

#456 Add null return value to PHPDoc
  src/ClientInterface.php
Labels: documentation

#646 Fix PHPUnit installation on PHP 8
  .github/workflows/tests.yml
Labels: tests

#554 update sort command to be a write operation
  src/Replication/ReplicationStrategy.php
  tests/Predis/Connection/Aggregate/MasterSlaveReplicationTest.php
  tests/Predis/Replication/ReplicationStrategyTest.php
Labels: bug, client-replication, redis-sentinel

#651 Make client configuration easier for phpiredis based connections.
  CHANGELOG.md
  README.md
  src/Configuration/Option/Connections.php
  tests/Predis/Configuration/Option/ConnectionsTest.php
Labels: feature, phpiredis
