Repository predis/predis, pull requests merged in 2022-12, with the labels that each got.

#811 Adding the release drafter
  .github/release-drafter-config.yml
  .github/workflows/release-drafter.yml
Labels: maintenance

#857 Fixing the release drafter, to honour the main branch
  .github/workflows/release-drafter.yml
Labels: maintenance

#835 Added mixin annotations for traits
  src/Command/Traits/ByLexByScore.php
  src/Command/Traits/Count.php
  src/Command/Traits/Keys.php
  src/Command/Traits/Limit.php
  src/Command/Traits/MinMaxModifier.php
  src/Command/Traits/Numkeys.php
  src/Command/Traits/Rev.php
  src/Command/Traits/WithScores.php
Labels: maintenance

#858 Refactored ZUNIONSTORE, ZINTERSTORE, removed Numkeys trait, improved Withscores response parsing
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/ZDIFF.php
  src/Command/Redis/ZDIFFSTORE.php
  src/Command/Redis/ZMPOP.php
  src/Command/Redis/ZUNIONSTORE.php
  src/Command/Traits/Aggregate.php
  src/Command/Traits/Keys.php
  src/Command/Traits/Numkeys.php
  src/Command/Traits/Weights.php
  src/Command/Traits/WithScores.php
  tests/Predis/Cluster/PredisStrategyTest.php
  tests/Predis/Command/Redis/SLOWLOG_Test.php
  tests/Predis/Command/Redis/ZDIFF_test.php
  tests/Predis/Command/Redis/ZINTERSTORE_Test.php
  tests/Predis/Command/Redis/ZUNIONSTORE_Test.php
  tests/Predis/Command/Traits/AggregateTest.php
  tests/Predis/Command/Traits/KeysTest.php
  tests/Predis/Command/Traits/NumkeysTest.php
  tests/Predis/Command/Traits/WeightsTest.php
  tests/Predis/Command/Traits/WithScoresTest.php
Labels: bug

#863 Extend Lists support by implementing LMOVE command
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/LMOVE.php
  tests/Predis/Command/Redis/LMOVE_Test.php
Labels: feature

#861 Extended Sorted Set support by adding ZINTERCARD command
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/ZINTERCARD.php
  src/Command/Traits/Limit.php
  tests/Predis/Command/Redis/ZINTERCARD_Test.php
  tests/Predis/Command/Traits/LimitTest.php
Labels: feature

#862 Extended Sorted Set support by adding BZPOPMIN command
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/BZPOPMIN.php
  src/Command/Traits/Keys.php
  tests/Predis/Command/Redis/BZPOPMIN_Test.php
  tests/Predis/Command/Traits/KeysTest.php
Labels: feature

#859 Extended Sorted Set support by adding ZINTER command
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/ZINTER.php
  tests/Predis/Command/Redis/ZINTER_Test.php
Labels: feature

#870 Extended Hash support by implementing HRANDFIELD command
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/HRANDFIELD.php
  src/Command/Traits/With/WithValues.php
  tests/PHPUnit/OneOfConstraint.php
  tests/PHPUnit/PredisTestCase.php
  tests/Predis/Command/Redis/HRANDFIELD_Test.php
  tests/bootstrap.php
Labels: feature

#871 Extended Set support by implementing SMISMEMBER command
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/SMISMEMBER.php
  tests/Predis/Command/Redis/SMISMEMBER_Test.php
Labels: feature

#867 Extend Geospatial support by implementing GEOSEARCH command
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Argument/ArrayableArgument.php
  src/Command/Argument/Geospatial/AbstractBy.php
  src/Command/Argument/Geospatial/ByBox.php
  src/Command/Argument/Geospatial/ByInterface.php
  src/Command/Argument/Geospatial/ByRadius.php
  src/Command/Argument/Geospatial/FromInterface.php
  src/Command/Argument/Geospatial/FromLonLat.php
  src/Command/Argument/Geospatial/FromMember.php
  src/Command/Redis/GEOSEARCH.php
  src/Command/Redis/ZDIFF.php
  src/Command/Redis/ZINTER.php
  src/Command/Redis/ZRANDMEMBER.php
  src/Command/Redis/ZRANGESTORE.php
  src/Command/Redis/ZUNION.php
  src/Command/Traits/By/ByLexByScore.php
  src/Command/Traits/By/GeoBy.php
  src/Command/Traits/Count.php
  src/Command/Traits/From/GeoFrom.php
  src/Command/Traits/Sorting.php
  src/Command/Traits/With/WithCoord.php
  src/Command/Traits/With/WithDist.php
  src/Command/Traits/With/WithHash.php
  src/Command/Traits/With/WithScores.php
  tests/Predis/Command/Redis/GEOSEARCH_Test.php
  tests/Predis/Command/Traits/By/GeoByTest.php
  tests/Predis/Command/Traits/ByLexByScoreTest.php
  tests/Predis/Command/Traits/CountTest.php
  tests/Predis/Command/Traits/From/GeoFromTest.php
  tests/Predis/Command/Traits/With/WithCoordTest.php
  tests/Predis/Command/Traits/With/WithDistTest.php
  tests/Predis/Command/Traits/With/WithHashTest.php
  tests/Predis/Command/Traits/With/WithScoresTest.php
Labels: feature

#866 Extended Key Space support by implementing COPY command
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/COPY.php
  src/Command/Traits/DB.php
  src/Command/Traits/Replace.php
  tests/PHPUnit/PredisCommandTestCase.php
  tests/Predis/Command/Redis/COPY_Test.php
  tests/Predis/Command/Traits/DbTest.php
  tests/Predis/Command/Traits/ReplaceTest.php
Labels: feature

#875 Extended server functionality by implementing FAILOVER command
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Argument/Server/To.php
  src/Command/Redis/FAILOVER.php
  src/Command/Traits/Timeout.php
  src/Command/Traits/To/ServerTo.php
  tests/Predis/Command/Redis/FAILOVER_Test.php
  tests/Predis/Command/Traits/TimeoutTest.php
  tests/Predis/Command/Traits/To/ServerToTest.php
Labels: feature
