Repository predis/predis, pull requests merged in 2023-08, with the labels that each got.

#1351 Client set lib and version on connection
  src/Connection/AbstractConnection.php
  src/Connection/Factory.php
  src/Connection/StreamConnection.php
  tests/Predis/ClientTest.php
  tests/Predis/Connection/FactoryTest.php
  tests/Predis/Connection/StreamConnectionTest.php
Labels: feature

#1349 2.2.1 version changes
  VERSION
  src/Client.php
Labels: maintenance

#1347 Client set name and version on connection
  src/Connection/AbstractConnection.php
  src/Connection/Factory.php
  src/Connection/StreamConnection.php
  tests/Predis/ClientTest.php
  tests/Predis/Connection/FactoryTest.php
  tests/Predis/Connection/StreamConnectionTest.php
Labels: feature

#1354 [3.x] Spellcheck as part of CI
  .github/spellcheck-settings.yml
  .github/wordlist.txt
  .github/workflows/linters.yml
  .github/workflows/spellcheck.yml
  .github/workflows/stack.yml
  .github/workflows/tests.yml
  FAQ.md
Labels: maintenance

#1358 Added missing redis-stack commands to KeyPrefix processor
  src/Command/Processor/KeyPrefixProcessor.php
Labels: feature

#1357 Added support for WAITAOF command
  examples/Commands/waitaof.php
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/WAITAOF.php
  tests/Predis/Command/Redis/WAITAOF_Test.php
Labels: feature

#1363 Updated CHANGELOG.md
  CHANGELOG.md
  src/Connection/Replication/SentinelReplication.php
Labels: maintenance

#1360 Added support for CLUSTER container command
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Cluster/ClusterStrategy.php
  src/Command/Redis/CLUSTER.php
  src/Command/Redis/Container/CLUSTER.php
  tests/Predis/Cluster/PredisStrategyTest.php
  tests/Predis/Cluster/RedisStrategyTest.php
  tests/Predis/Command/Redis/CLUSTER_Test.php
  tests/Predis/Command/Redis/Container/CLUSTER_Test.php
Labels: feature

#1369 Added EXPIRETIME command to KeyPrefixProcessor
  src/Command/Processor/KeyPrefixProcessor.php
  tests/Predis/ClientTest.php
  tests/Predis/Command/Processor/KeyPrefixProcessorTest.php
  tests/Predis/Command/Redis/ACL_Test.php
  tests/Predis/Command/Redis/OBJECT_Test.php
Labels: bug
