Repository predis/predis, pull requests merged in 2023-02, with the labels that each got.

#1080 Extended BloomFilters support by implementing CF.DEL command
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/CuckooFilter/CFDEL.php
  tests/Predis/Command/Redis/CuckooFilter/CFDEL_Test.php
Labels: feature

#1086 Extended CuckooFilters support by implementing CF.RESERVE command
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/CuckooFilter/CFRESERVE.php
  src/Command/Traits/BloomFilters/BucketSize.php
  src/Command/Traits/BloomFilters/MaxIterations.php
  tests/Predis/Command/Redis/CuckooFilter/CFRESERVE_Test.php
  tests/Predis/Command/Traits/BloomFilters/BucketSizeTest.php
  tests/Predis/Command/Traits/BloomFilters/MaxIterationsTest.php
Labels: feature

#1087 Extended CuckooFilters support by implementing CF.INSERTNX command
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/CuckooFilter/CFINSERTNX.php
  tests/Predis/Command/Redis/CuckooFilter/CFINSERTNX_Test.php
Labels: feature

#1090 Extended Count-Min Sketch support by implementing CMS.INITBYPROB command
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/CountMinSketch/CMSINITBYPROB.php
  tests/Predis/Command/Redis/CountMinSketch/CMSINITBYPROB_Test.php
Labels: feature

#1092 Extended Count-Min Sketch support by implementing CMS.MERGE command
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/CountMinSketch/CMSMERGE.php
  tests/Predis/Command/Redis/CountMinSketch/CMSINCRBY_Test.php
  tests/Predis/Command/Redis/CountMinSketch/CMSMERGE_Test.php
  tests/Predis/Command/Redis/CountMinSketch/CMSQUERY_Test.php
Labels: feature

#1093 Added support for TDigest sketch, implemented TDIGEST.CREATE and TDIGEST.INFO commands
  src/ClientConfiguration.php
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/TDigest/TDIGESTCREATE.php
  src/Command/Redis/TDigest/TDIGESTINFO.php
  tests/Predis/Command/Redis/TDigest/TDIGESTCREATE_Test.php
  tests/Predis/Command/Redis/TDigest/TDIGESTINFO_Test.php
Labels: feature

#1094 Extended TDigest Sketch support by implementing TDIGEST.ADD command
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/TDigest/TDIGESTADD.php
  tests/Predis/Command/Redis/TDigest/TDIGESTADD_Test.php
Labels: feature

#1098 Extended TDigest support by implementing TDIGEST.CDF command
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/TDigest/TDIGESTCDF.php
  tests/Predis/Command/Redis/TDigest/TDIGESTCDF_Test.php
Labels: feature

#1099 Extended support by implementing TDIGEST.MAX command
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/TDigest/TDIGESTMAX.php
  tests/Predis/Command/Redis/TDigest/TDIGESTMAX_Test.php
Labels: feature

#1103 Extended TDigest support by implementing TDIGEST.RANK command
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/TDigest/TDIGESTRANK.php
  tests/Predis/Command/Redis/TDigest/TDIGESTRANK_Test.php
Labels: feature

#1104 Extended TDigest support by implementing TDIGEST.RESET command
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/TDigest/TDIGESTRESET.php
  tests/Predis/Command/Redis/TDigest/TDIGESTRESET_Test.php
Labels: feature

#1101 Extended support by implementing TDIGEST.QUANTILE command
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/TDigest/TDIGESTQUANTILE.php
  tests/Predis/Command/Redis/TDigest/TDIGESTQUANTILE_Test.php
Labels: feature

#1105 Extended TDigest support by implementing TDIGEST.REVRANK command
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/TDigest/TDIGESTREVRANK.php
  tests/Predis/Command/Redis/TDigest/TDIGESTREVRANK_Test.php
Labels: feature

#1106 Extended TDigest support by implementing TDIGEST.TRIMMED_MEAN command
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/TDigest/TDIGESTTRIMMED_MEAN.php
  tests/Predis/Command/Redis/TDigest/TDIGESTTRIMMED_MEAN_Test.php
Labels: feature

#1107 Extended TopK support by implementing TOPK.RESERVE, TOPK.INFO commands
  src/ClientConfiguration.php
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/TopK/TOPKINFO.php
  src/Command/Redis/TopK/TOPKRESERVE.php
  tests/Predis/Command/Redis/TopK/TOPKINFO_Test.php
  tests/Predis/Command/Redis/TopK/TOPKRESERVE_Test.php
Labels: feature

#1108 Extended TopK support by implementing TOPK.ADD, TOPK.LIST commands
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/TopK/TOPKADD.php
  src/Command/Redis/TopK/TOPKLIST.php
  tests/Predis/Command/Redis/TopK/TOPKADD_Test.php
  tests/Predis/Command/Redis/TopK/TOPKLIST_Test.php
Labels: feature

#1109 Extended TopK support by implementing TOPK.INCRBY command
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/TopK/TOPKINCRBY.php
  tests/Predis/Command/Redis/TopK/TOPKINCRBY_Test.php
Labels: feature

#1110 Extended TopK support by implementing TOPK.QUERY command
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/TopK/TOPKQUERY.php
  tests/Predis/Command/Redis/TopK/TOPKQUERY_Test.php
Labels: feature

#1102 Extended TDigest support by implementing TDIGEST.MERGE command
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/TDigest/TDIGESTMERGE.php
  tests/Predis/Command/Redis/TDigest/TDIGESTMERGE_Test.php
Labels: feature

#1172 Container commands naming fixes
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/Container/ContainerFactory.php
  src/Command/Redis/Container/FUNCTIONS.php
  tests/Predis/Command/Redis/Container/ContainerFactoryTest.php
Labels: feature

#1143 Added support for RediSearch, implemented FT.CREATE command
  phpunit.xml.dist
  src/ClientConfiguration.php
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Argument/Search/CommonArguments.php
  src/Command/Argument/Search/CreateArguments.php
  src/Command/Argument/Search/Schema.php
  src/Command/Redis/Search/FTCREATE.php
  tests/PHPUnit/PredisTestCase.php
  tests/Predis/Command/Argument/Search/CommonArgumentsTest.php
  tests/Predis/Command/Argument/Search/CreateArgumentsTest.php
  tests/Predis/Command/Argument/Search/SchemaTest.php
  tests/Predis/Command/Redis/MOVE_Test.php
  tests/Predis/Command/Redis/SELECT_Test.php
  tests/Predis/Command/Redis/Search/FTCREATE_Test.php
Labels: feature

#1145 Extended RediSearch support by implementing FT.SEARCH command
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Argument/Search/CommonArguments.php
  src/Command/Argument/Search/SearchArguments.php
  src/Command/Redis/Search/FTSEARCH.php
  tests/Predis/Command/Argument/Search/CommonArgumentsTest.php
  tests/Predis/Command/Argument/Search/CreateArgumentsTest.php
  tests/Predis/Command/Argument/Search/SearchArgumentsTest.php
  tests/Predis/Command/Redis/Search/FTSEARCH_Test.php
Labels: feature

#1175 match `MasterSlaveReplication`
  src/Connection/Replication/SentinelReplication.php
Labels: documentation

#1148 Extended RediSearch support by implementing FT.INFO command
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/Search/FTINFO.php
  tests/Predis/Command/Redis/Search/FTINFO_Test.php
Labels: feature

#1150 Extended RediSearch support by implementing FT.ALIASADD command
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/Search/FTALIASADD.php
  tests/Predis/Command/Redis/Search/FTALIASADD_Test.php
Labels: feature

#1151 Extended RediSearch support by implementing FT.ALIASDEL command
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/Search/FTALIASDEL.php
  tests/Predis/Command/Redis/Search/FTALIASDEL_Test.php
Labels: feature

#1152 Extended RediSearch support by implementing FT.ALIASUPDATE command
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/Search/FTALIASUPDATE.php
  tests/Predis/Command/Redis/Search/FTALIASUPDATE_Test.php
Labels: feature

#1155 Extended RediSearch support by implementing FT.DICTADD command
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/Search/FTDICTADD.php
  tests/Predis/Command/Redis/Search/FTDICTADD_Test.php
Labels: feature

#1156 Extended RediSearch support by implementing FT.DICTDEL support
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/Search/FTDICTDEL.php
  tests/Predis/Command/Redis/Search/FTDICTDEL_Test.php
Labels: feature

#1157 Extended RediSearch support by implementing FT.DICTDUMP command
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/Search/FTDICTDUMP.php
  tests/Predis/Command/Redis/Search/FTDICTDUMP_Test.php
Labels: feature

#1158 Extended RediSearch support by implementing FT.DROPINDEX command
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Argument/Search/DropArguments.php
  src/Command/Redis/Search/FTDROPINDEX.php
  tests/Predis/Command/Argument/Search/DropArgumentsTest.php
  tests/Predis/Command/Redis/Search/FTDROPINDEX_Test.php
Labels: feature

#1161 Extended RediSearch support by implementing FT.PROFILE command
  examples/Commands/Search/ft_profile.php
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Argument/Search/ProfileArguments.php
  src/Command/Redis/Search/FTPROFILE.php
  tests/Predis/Command/Argument/Search/ProfileArgumentsTest.php
  tests/Predis/Command/Redis/Search/FTPROFILE_Test.php
Labels: feature

#1162 Extended RediSearch support by implementing FT.SPELLCHECK command
  examples/Commands/Search/ft_spellcheck.php
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Argument/Search/SpellcheckArguments.php
  src/Command/Redis/Search/FTSPELLCHECK.php
  tests/Predis/Command/Argument/Search/SpellcheckArgumentsTest.php
  tests/Predis/Command/Redis/Search/FTPROFILE_Test.php
  tests/Predis/Command/Redis/Search/FTSPELLCHECK_Test.php
Labels: feature

#1164 Extended RediSearch support by implementing FT.SYNUPDATE command
  examples/Commands/Search/ft_synupdate.php
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Argument/Search/CommonArguments.php
  src/Command/Argument/Search/CreateArguments.php
  src/Command/Argument/Search/SynUpdateArguments.php
  src/Command/Redis/Search/FTSYNUPDATE.php
  tests/Predis/Command/Argument/Search/CommonArgumentsTest.php
  tests/Predis/Command/Argument/Search/CreateArgumentsTest.php
  tests/Predis/Command/Redis/Search/FTSYNUPDATE_Test.php
Labels: feature

#1167 Extended RediSearch by implementing FT.SUGADD command
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Argument/Search/CommonArguments.php
  src/Command/Argument/Search/SearchArguments.php
  src/Command/Argument/Search/SugAddArguments.php
  src/Command/Redis/Search/FTSUGADD.php
  tests/Predis/Command/Argument/Search/CommonArgumentsTest.php
  tests/Predis/Command/Argument/Search/SearchArgumentsTest.php
  tests/Predis/Command/Argument/Search/SugAddArgumentsTest.php
  tests/Predis/Command/Redis/Search/FTSUGADD_Test.php
Labels: feature

#1174 Extended RediSearch support by implementing FT.CONFIG HELP command
  examples/Commands/Search/ft_config_help.php
  src/Command/Container/Search/FTCONFIG.php
  tests/Predis/Command/Redis/Search/FTCONFIG_Test.php
Labels: feature

#1182 Extended Json support by implementing JSON.DEBUG command
  examples/Commands/Json/json_debug_memory.php
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Container/Json/JSONDEBUG.php
  src/Command/Redis/Json/JSONDEBUG.php
  tests/Predis/Command/Redis/Json/JSONDEBUG_Test.php
Labels: feature

#1181 Added CODEOWNERS file
  .github/CODEOWNERS
Labels: maintenance

#1179 Deprecate webdis and phpiredis
  CHANGELOG.md
  README.md
  src/Cluster/Hash/PhpiredisCRC16.php
  src/Connection/PhpiredisSocketConnection.php
  src/Connection/PhpiredisStreamConnection.php
  src/Connection/WebdisConnection.php
Labels: phpiredis
