Repository predis/predis, pull requests merged in 2023-01, with the labels that each got.

#1013 Extended core support by implementing LMPOP command
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/LMPOP.php
  src/Command/Traits/LeftRight.php
  tests/Predis/Command/Redis/LMPOP_Test.php
  tests/Predis/Command/Traits/LeftRightTest.php
Labels: feature

#1017 Fix Client template
  src/Client.php
Labels: documentation, maintenance

#1018 Fix support options array in `ZINTERSTORE` and `ZUNIONSTORE`
  src/Command/Redis/ZUNIONSTORE.php
  tests/Predis/Command/Redis/ZINTERSTORE_Test.php
  tests/Predis/Command/Redis/ZUNIONSTORE_Test.php
Labels: bug

#1022 Add phpstan level 0
  .github/workflows/coding-standards.yml
  phpstan.dist.neon
  src/Cluster/SlotMap.php
  src/Cluster/StrategyInterface.php
  src/Command/Factory.php
  src/Configuration/Option/Replication.php
  src/Connection/PhpiredisSocketConnection.php
  src/Connection/Replication/MasterSlaveReplication.php
  tests/Predis/Collection/Iterator/HashKeyTest.php
  tests/Predis/Command/Redis/EVALSHA_Test.php
  tests/Predis/Connection/FactoryTest.php
  tests/Predis/Protocol/Text/ProtocolProcessorTest.php
Labels: maintenance

#1031 Extended core support by implementing PEXPIRETIME command
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/PEXPIRETIME.php
  tests/Predis/Command/Redis/PEXPIRETIME_Test.php
Labels: feature

#1029 Extended core support by implementing EXPIRETIME command
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/EXPIRETIME.php
  tests/Predis/Command/Redis/EXPIRETIME_Test.php
Labels: feature

#1027 Extended Sets support by implementing SINTERCARD command
  .gitignore
  composer.json
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/SINTERCARD.php
  tests/Predis/Command/Redis/SINTERCARD_Test.php
Labels: feature, maintenance

#1032 Extended core support by implementing EVAL_RO command
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/EVAL_RO.php
  tests/Predis/Command/Redis/EVAL_RO_Test.php
Labels: feature

#1035 Extended core support by implementing LCS command
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/LCS.php
  tests/Predis/Command/Redis/LCS_Test.php
Labels: feature

#1025 Fix PHPStan level 2 problems
  .github/workflows/coding-standards.yml
  src/Client.php
  src/Cluster/ClusterStrategy.php
  src/Cluster/SlotMap.php
  src/Command/Command.php
  src/Command/Factory.php
  src/Command/FactoryInterface.php
  src/Command/RawCommand.php
  src/Command/Redis/LMPOP.php
  src/Configuration/OptionsInterface.php
  src/Connection/Cluster/PredisCluster.php
  src/Connection/Cluster/RedisCluster.php
  src/Connection/CompositeConnectionInterface.php
  src/Connection/ParametersInterface.php
  src/Connection/PhpiredisSocketConnection.php
  src/Connection/Replication/MasterSlaveReplication.php
  src/Connection/Replication/SentinelReplication.php
  src/Connection/StreamConnection.php
  src/PubSub/AbstractConsumer.php
Labels: maintenance

#874 Added support for Bloom Filters module, added support for BF.ADD, BF.EXISTS commands
  src/ClientConfiguration.php
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/BloomFilter/BFADD.php
  src/Command/Redis/BloomFilter/BFEXISTS.php
  tests/PHPUnit/PredisTestCase.php
  tests/Predis/Command/Redis/BloomFilter/BFADD_Test.php
  tests/Predis/Command/Redis/BloomFilter/BFEXISTS_Test.php
Labels: feature

#1045 Added support for new arguments for BITPOS, BITCOUNT commands
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/BITCOUNT.php
  src/Command/Redis/BITPOS.php
  src/Command/Traits/BitByte.php
  tests/Predis/Command/Redis/BITCOUNT_Test.php
  tests/Predis/Command/Redis/BITPOS_Test.php
  tests/Predis/Command/Traits/BitByteTest.php
Labels: feature

#1046 Added support for new arguments for EXPIRE, EXPIREAT commands
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/EXPIRE.php
  src/Command/Redis/EXPIREAT.php
  src/Command/Traits/Expire/ExpireOptions.php
  tests/Predis/Command/Redis/EXPIREAT_Test.php
  tests/Predis/Command/Redis/EXPIRE_Test.php
Labels: feature

#907 Added support for Cuckoo Filter, added CF.ADD and CF.EXISTS commands
  src/ClientConfiguration.php
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/CuckooFilter/CFADD.php
  src/Command/Redis/CuckooFilter/CFEXISTS.php
  tests/Predis/Command/Redis/CuckooFilter/CFADD_Test.php
  tests/Predis/Command/Redis/CuckooFilter/CFEXISTS_Test.php
Labels: feature

#886 Extended Bloom filters by implementing BF.INFO command
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/BloomFilter/BFINFO.php
  tests/Predis/Command/Redis/BloomFilter/BFINFO_Test.php
Labels: feature

#887 Extend Bloom filters by imlplementing BFMADD and BFMEXISTS commands
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/BloomFilter/BFMADD.php
  src/Command/Redis/BloomFilter/BFMEXISTS.php
  tests/Predis/Command/Redis/BloomFilter/BFMADD_Test.php
  tests/Predis/Command/Redis/BloomFilter/BFMEXISTS_Test.php
Labels: feature

#888 Extended Bloom Filters by implementing BF.RESERVE command
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/BloomFilter/BFRESERVE.php
  src/Command/Traits/BloomFilters/Expansion.php
  tests/Predis/Command/Redis/BloomFilter/BFRESERVE_Test.php
  tests/Predis/Command/Traits/BloomFilters/ExpansionTest.php
Labels: feature

#889 Extended Bloom Filter by implementing BF.SCANDUMP command
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/BloomFilter/BFSCANDUMP.php
  tests/Predis/Command/Redis/BloomFilter/BFSCANDUMP_Test.php
Labels: feature

#890 Extended Bloom Filters by implementing BF.LOADCHUNK command
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/BloomFilter/BFLOADCHUNK.php
  tests/Predis/Command/Redis/BloomFilter/BFLOADCHUNK_Test.php
Labels: feature

#891 Extended Bloom Filter support by implementing BF.INSERT command
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/BloomFilter/BFINSERT.php
  src/Command/Traits/BloomFilters/Capacity.php
  src/Command/Traits/BloomFilters/Error.php
  src/Command/Traits/BloomFilters/Items.php
  tests/Predis/Command/Redis/BloomFilter/BFINSERT_Test.php
  tests/Predis/Command/Traits/BloomFilters/CapacityTest.php
  tests/Predis/Command/Traits/BloomFilters/ErrorTest.php
  tests/Predis/Command/Traits/BloomFilters/ItemsTest.php
Labels: feature

#909 Extended RedisJson support by implementing JSON.DEL command
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/Json/JSONDEL.php
  tests/Predis/Command/Redis/Json/JSONDEL_Test.php
Labels: feature

#911 Extended RedisJson support by implementing JSON.OBJKEYS command
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/Json/JSONOBJKEYS.php
  tests/Predis/Command/Redis/Json/JSONOBJKEYS_Test.php
Labels: feature

#913 Extended RedisJson support by implementing JSON.OBJLEN command
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/Json/JSONOBJLEN.php
  tests/Predis/Command/Redis/Json/JSONOBJLEN_Test.php
Labels: feature

#915 Extended RedisJson support by implementing JSON.STRAPPEND command
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/Json/JSONSTRAPPEND.php
  tests/Predis/Command/Redis/Json/JSONSTRAPPEND_Test.php
Labels: feature

#917 Extended RedisJson support by implementing JSON.STRLEN command
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/Json/JSONSTRLEN.php
  tests/Predis/Command/Redis/Json/JSONSTRLEN_Test.php
Labels: feature

#919 Extended RedisJson support by implementing JSON.NUMINCRBY command
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/Json/JSONNUMINCRBY.php
  tests/Predis/Command/Redis/Json/JSONNUMINCRBY_Test.php
Labels: feature

#927 Extended RedisJson support by implementing JSON.ARRINDEX command
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/Json/JSONARRINDEX.php
  tests/Predis/Command/Redis/Json/JSONARRINDEX_Test.php
Labels: feature

#929 Extended RedisJson support by implementing JSON.ARRINSERT command
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/Json/JSONARRINSERT.php
  tests/Predis/Command/Redis/Json/JSONARRINSERT_Test.php
Labels: feature

#931 Extended RedisJson support by implementing JSON.ARRLEN command
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/Json/JSONARRLEN.php
  tests/Predis/Command/Redis/Json/JSONARRLEN_Test.php
Labels: feature

#933 Extended RedisJson support by implementing JSON.ARRPOP command
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/Json/JSONARRPOP.php
  tests/Predis/Command/Redis/Json/JSONARRPOP_Test.php
Labels: feature

#936 Extended RedisJson support by implementing JSON.ARRTRIM command
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/Json/JSONARRTRIM.php
  tests/Predis/Command/Redis/Json/JSONARRTRIM_Test.php
Labels: feature

#1004 Extended RedisJson support by implementing JSON.CLEAR command
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/Json/JSONCLEAR.php
  tests/Predis/Command/Redis/Json/JSONCLEAR_Test.php
Labels: feature

#1006 Extended RedisJson support by implementing JSON.RESP command
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/Json/JSONRESP.php
  tests/Predis/Command/Redis/Json/JSONRESP_Test.php
Labels: feature

#1008 Extended RedisJson support by implementing JSON.TOGGLE command
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/Json/JSONTOGGLE.php
  tests/Predis/Command/Redis/Json/JSONTOGGLE_Test.php
Labels: feature

#1010 Extended RedisJson support by implementing JSON.TYPE command
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/Json/JSONTYPE.php
  tests/Predis/Command/Redis/Json/JSONTYPE_Test.php
Labels: feature

#1048 Add Support for CF.ADDNX
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/CuckooFilter/CFADDNX.php
  tests/Predis/Command/Redis/CuckooFilter/CFADDNX_Test.php
Labels: feature

#1052 Extended BloomFilters support by implementing CF.COUNT command
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/CuckooFilter/CFCOUNT.php
  tests/Predis/Command/Redis/CuckooFilter/CFCOUNT_Test.php
Labels: feature

#1082 Extended BloomFilters support by implementing CF.INFO command
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/BloomFilter/BFINFO.php
  src/Command/Redis/CuckooFilter/CFINFO.php
  tests/Predis/Command/Redis/CuckooFilter/CFINFO_Test.php
Labels: feature

#1049 Added support for container commands
  src/Client.php
  src/ClientContextInterface.php
  src/ClientInterface.php
  src/Command/Redis/Container/AbstractContainer.php
  src/Command/Redis/Container/ContainerFactory.php
  src/Command/Redis/Container/ContainerInterface.php
  src/Command/Redis/Container/FunctionContainer.php
  src/Command/Redis/FCALL.php
  src/Command/Redis/FUNCTIONS.php
  src/Command/RedisFactory.php
  src/Command/Strategy/ContainerCommands/Functions/DeleteStrategy.php
  src/Command/Strategy/ContainerCommands/Functions/LoadStrategy.php
  src/Command/Strategy/StrategyResolverInterface.php
  src/Command/Strategy/SubcommandStrategyInterface.php
  src/Command/Strategy/SubcommandStrategyResolver.php
  tests/Predis/Command/Redis/Container/AbstractContainerTest.php
  tests/Predis/Command/Redis/Container/ContainerFactoryTest.php
  tests/Predis/Command/Redis/FCALL_Test.php
  tests/Predis/Command/Redis/FUNCTIONS_Test.php
  tests/Predis/Command/Strategy/ContainerCommands/Functions/DeleteStrategyTest.php
  tests/Predis/Command/Strategy/ContainerCommands/Functions/LoadStrategyTest.php
  tests/Predis/Command/Strategy/SubcommandStrategyResolverTest.php
Labels: feature

#1051 Added stream commands to KeyPrefixProcessor
  src/Command/Processor/KeyPrefixProcessor.php
Labels: bug
