Repository predis/predis, pull requests merged in 2025-03, with the labels that each got.

#1517 Enable stack and cluster tests on 3 latest API versions
  .github/docker-compose.yml
  .github/workflows/tests.yml
  phpunit.relay.xml
  phpunit.xml.dist
  src/Command/Redis/Search/FTEXPLAIN.php
  tests/PHPUnit/PredisTestCase.php
  tests/Predis/Command/Redis/Search/FTAGGREGATE_Test.php
  tests/Predis/Command/Redis/Search/FTALIASADD_Test.php
  tests/Predis/Command/Redis/Search/FTALIASUPDATE_Test.php
  tests/Predis/Command/Redis/Search/FTALTER_Test.php
  tests/Predis/Command/Redis/Search/FTCURSOR_Test.php
  tests/Predis/Command/Redis/Search/FTDICTDUMP_Test.php
  tests/Predis/Command/Redis/Search/FTDROPINDEX_Test.php
  tests/Predis/Command/Redis/Search/FTEXPLAIN_Test.php
  tests/Predis/Command/Redis/Search/FTPROFILE_Test.php
  tests/Predis/Command/Redis/Search/FTSEARCH_Test.php
  tests/Predis/Command/Redis/Search/FTSUGGET_Test.php
  tests/Predis/Command/Redis/Search/FTSYNDUMP_Test.php
  tests/Predis/Command/Redis/Search/FTSYNUPDATE_Test.php
  tests/Predis/Command/Redis/Search/FTTAGVALS_Test.php
  tests/Predis/Command/Redis/TimeSeries/TSINFO_Test.php
Labels: maintenance

#1519 fix(stream): Removed resource disconnection on GC
  src/Connection/Resource/Stream.php
  tests/Predis/ClientTest.php
  tests/Predis/Connection/Resource/StreamTest.php
Labels: bug

#1497 Added support for transactions in OSS Cluster
  CHANGELOG.md
  README.md
  src/Cluster/ClusterStrategy.php
  src/Cluster/PredisStrategy.php
  src/Cluster/StrategyInterface.php
  src/Connection/Cluster/ClusterInterface.php
  src/Connection/Cluster/PredisCluster.php
  src/Connection/Cluster/RedisCluster.php
  src/Transaction/Exception/TransactionException.php
  src/Transaction/MultiExec.php
  src/Transaction/Response/BypassTransactionResponse.php
  src/Transaction/Strategy/ClusterConnectionStrategy.php
  src/Transaction/Strategy/ConnectionStrategyResolver.php
  src/Transaction/Strategy/NodeConnectionStrategy.php
  src/Transaction/Strategy/NonClusterConnectionStrategy.php
  src/Transaction/Strategy/ReplicationConnectionStrategy.php
  src/Transaction/Strategy/StrategyInterface.php
  src/Transaction/Strategy/StrategyResolverInterface.php
  tests/PHPUnit/PredisTestCase.php
  tests/Predis/Cluster/PredisStrategyTest.php
  tests/Predis/Cluster/RedisStrategyTest.php
  tests/Predis/Transaction/MultiExecTest.php
  tests/Predis/Transaction/Strategy/ClusterConnectionStrategyTest.php
  tests/Predis/Transaction/Strategy/ConnectionStrategyResolverTest.php
  tests/Predis/Transaction/Strategy/NodeConnectionStrategyTest.php
  tests/Predis/Transaction/Strategy/ReplicationConnectionStrategyTest.php
Labels: breakingchange

#1493 optimize redis cluster slotmap with compact slot range object
  src/Cluster/NullSlotRange.php
  src/Cluster/SimpleSlotMap.php
  src/Cluster/SlotMap.php
  src/Cluster/SlotRange.php
  tests/Predis/Cluster/SimpleSlotMapTest.php
  tests/Predis/Cluster/SlotRangeTest.php
Labels: feature, redis-cluster
